import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {createWorld} from './world';
import type {Weather} from './environment';
import {animateAsset,type Clip} from '../../../../../packages/asset-tools/src/actors';
import {setFoliageTime} from '../../../../../packages/asset-tools/src/nature';
import {ellipsoid,joint,mesh} from '../../../../../packages/asset-tools/src/geometry';
import {assetInfo,type AssetKind,mat,beam} from '../../../../../packages/asset-tools/src/models';
export type View='settlement'|'harbor'|'regiment'|'resources'|'sky'|'studio';
export type Light='day'|'golden'|'overcast';
export interface Metrics{fps:number;frameMs:number;drawCalls:number;triangles:number;geometries:number;textures:number;backend:string;cpuMs:number;pixels:number;trees:number;units:number;buildings:number;}
export class Showcase{
 renderer:T.WebGLRenderer;scene=new T.Scene();camera=new T.PerspectiveCamera(42,1,.2,1600);controls:OrbitControls;world:ReturnType<typeof createWorld>;
 sun=new T.DirectionalLight('#ffe0ad',3.1);fill=new T.HemisphereLight('#cbdde2','#70734c',2);studio=new T.Group();view:View='settlement';asset:AssetKind='hall';motion=true;wireframe=false;quality='high';
 weather:Weather='clear';clip:Clip='idle';private preview:T.Group|null=null;private currentLight:Light='day';
 private frame=0;private elapsed=0;private last=0;private sample=0;private frames=0;private targetPos:T.Vector3|null=null;private targetLook:T.Vector3|null=null;private smoke:T.Points;private birds=new T.Group();private keySet=new Set<string>();private disposer:(()=>void)[]=[];private first=true;private lastShadow=-1;private cpuMs=0;
 constructor(private host:HTMLElement,private onMetrics:(m:Metrics)=>void,private onPick:(kind:AssetKind)=>void,private onReady:()=>void){
 this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,preserveDrawingBuffer:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(1.6);this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFShadowMap;this.renderer.shadowMap.autoUpdate=false;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.12;this.renderer.outputColorSpace=T.SRGBColorSpace;host.append(this.renderer.domElement);this.renderer.domElement.tabIndex=0;this.renderer.domElement.setAttribute('aria-label','Interactive 3D coastal settlement. Drag to orbit, scroll to zoom, WASD to pan.');
 this.scene.background=new T.Color('#c4d2cf');this.scene.fog=new T.FogExp2('#c4d2cf',.0044);this.sun.position.set(-32,62,28);this.sun.castShadow=true;this.sun.shadow.mapSize.set(2048,2048);Object.assign(this.sun.shadow.camera,{left:-62,right:62,top:62,bottom:-62,near:.5,far:180});this.sun.shadow.bias=-.00025;this.sun.shadow.normalBias=.09;this.scene.add(this.sun,this.fill,this.sun.target);
 this.world=createWorld(this.renderer);this.scene.add(this.world.group);this.controls=new OrbitControls(this.camera,this.renderer.domElement);this.controls.enableDamping=true;this.controls.dampingFactor=.08;this.controls.minDistance=6;this.controls.maxDistance=115;this.controls.maxPolarAngle=Math.PI*.45;this.controls.minPolarAngle=.22;this.controls.screenSpacePanning=false;this.controls.mouseButtons={LEFT:T.MOUSE.ROTATE,MIDDLE:T.MOUSE.PAN,RIGHT:T.MOUSE.PAN};this.controls.target.set(-3,1,0);this.camera.position.set(44,41,59);this.controls.update();
 this.scene.add(this.studio);this.studio.visible=false;const stage=new T.Mesh(new T.CylinderGeometry(9,9.3,.35,80),mat('#9d9d8a'));stage.position.y=-.2;stage.receiveShadow=true;stage.name='stage';this.studio.add(stage);
 const smokeGeo=new T.BufferGeometry();const smokePos=new Float32Array(36*3);smokeGeo.setAttribute('position',new T.BufferAttribute(smokePos,3));const smokeMat=new T.ShaderMaterial({transparent:true,depthWrite:false,uniforms:{},vertexShader:`varying float vFade;void main(){vec4 mv=modelViewMatrix*vec4(position,1.);gl_Position=projectionMatrix*mv;gl_PointSize=130./max(1.,-mv.z);vFade=clamp((9.-position.y)/5.,0.,1.);}`,fragmentShader:`varying float vFade;void main(){float r=length(gl_PointCoord-.5)*2.;gl_FragColor=vec4(.76,.75,.66,(1.-smoothstep(.05,1.,r))*.13*vFade);}`});this.smoke=new T.Points(smokeGeo,smokeMat);this.world.group.add(this.smoke);
 for(let i=0;i<9;i++){const b=new T.Group();ellipsoid(b,0,0,0,.075,.075,.20,'#e6e3d1');ellipsoid(b,0,.04,.18,.065,.064,.08,'#e6e3d1');beam(b,[0,.035,.23],[0,.025,.32],.020,'#c6a45d',.002);for(const s of [-1,1]){const wing=joint(b,`wing${s}`,s*.04,0,0);const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute([0,0,.08,s*.30,.02,.07,s*.65,-.02,-.17,0,0,-.13,s*.34,0,-.20,s*.65,-.02,-.17],3));g.computeVertexNormals();const m=mat('#d0d4c6');m.side=T.DoubleSide;mesh(g,m,wing);}this.birds.add(b);}this.world.group.add(this.birds);
 const resize=()=>{const w=host.clientWidth,h=host.clientHeight;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();this.renderer.setSize(w,h);};const ro=new ResizeObserver(resize);ro.observe(host);this.disposer.push(()=>ro.disconnect());resize();
 const start=()=>{this.targetPos=null;this.targetLook=null;};this.controls.addEventListener('start',start);
 let downX=0,downY=0;const down=(e:PointerEvent)=>{downX=e.clientX;downY=e.clientY;};const up=(e:PointerEvent)=>{if(e.button!==0||Math.hypot(e.clientX-downX,e.clientY-downY)>4||this.view==='studio')return;const r=this.renderer.domElement.getBoundingClientRect(),pointer=new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new T.Raycaster();ray.setFromCamera(pointer,this.camera);const hit=ray.intersectObjects(this.world.pickables)[0];if(hit)this.onPick(hit.object.userData.kind);};
 this.renderer.domElement.addEventListener('pointerdown',down);this.renderer.domElement.addEventListener('pointerup',up);this.disposer.push(()=>{this.renderer.domElement.removeEventListener('pointerdown',down);this.renderer.domElement.removeEventListener('pointerup',up);});
 const keyDown=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLButtonElement)return;this.keySet.add(e.key.toLowerCase());if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','Home'].includes(e.key))e.preventDefault();if(e.key==='Home')this.setView('settlement');};const keyUp=(e:KeyboardEvent)=>this.keySet.delete(e.key.toLowerCase());const blur=()=>this.keySet.clear();window.addEventListener('keydown',keyDown);window.addEventListener('keyup',keyUp);window.addEventListener('blur',blur);this.disposer.push(()=>{window.removeEventListener('keydown',keyDown);window.removeEventListener('keyup',keyUp);window.removeEventListener('blur',blur);});
 const lost=(e:Event)=>{e.preventDefault();cancelAnimationFrame(this.frame);host.dataset.context='lost';};const restored=()=>location.reload();this.renderer.domElement.addEventListener('webglcontextlost',lost);this.renderer.domElement.addEventListener('webglcontextrestored',restored);this.disposer.push(()=>{this.renderer.domElement.removeEventListener('webglcontextlost',lost);this.renderer.domElement.removeEventListener('webglcontextrestored',restored);});
 this.renderer.compile(this.scene,this.camera);this.frame=requestAnimationFrame(this.tick);
 }
 setView(view:View){this.view=view;this.world.group.visible=view!=='studio';this.studio.visible=view==='studio';this.controls.autoRotate=view==='studio'&&this.motion;this.controls.autoRotateSpeed=.6;this.controls.minDistance=view==='studio'?3:8;this.controls.maxDistance=view==='studio'?45:115;this.sun.shadow.needsUpdate=true;this.renderer.shadowMap.needsUpdate=true;
 if(view==='studio'){this.setAsset(this.asset);this.scene.background=new T.Color('#bac0b3');this.scene.fog=null;return;}
 this.scene.fog=new T.FogExp2(this.scene.background as T.Color,.0044);
 this.setLight(this.currentLight);
 const presets={settlement:[[44,41,59],[-3,1,0]],harbor:[[54,21,48],[25,2,19]],regiment:[[19,12,33],[3,1,18]],resources:[[-13,22,45],[-30,1,13]],sky:[[54,15,64],[-5,8,-8]]};const [p,t]=presets[view];this.targetPos=new T.Vector3(...p);this.targetLook=new T.Vector3(...t);
 }
 setAsset(kind:AssetKind){this.asset=kind;if(this.preview)this.studio.remove(this.preview);const model=this.world.models.get(kind)!.clone();model.name=kind;this.preview=model;this.studio.add(model);const bounds=new T.Box3().setFromObject(model),size=bounds.getSize(new T.Vector3());const radius=Math.max(size.x,size.y,size.z);const stage=this.studio.getObjectByName('stage')!;stage.scale.setScalar(Math.max(.12,radius/10));stage.position.y=bounds.min.y-.19;this.targetLook=new T.Vector3(0,(bounds.min.y+bounds.max.y)*.5,0);this.targetPos=new T.Vector3(radius*.97,size.y*.65+radius*.30,radius*1.72);this.controls.autoRotate=false;this.applyWireframe();}
 setLight(light:Light){this.renderer.shadowMap.needsUpdate=true;this.currentLight=light;const weather=this.weather;const grey=weather!=='clear'||light==='overcast';if(light==='golden'){this.sun.color.set('#ffd19a');this.sun.intensity=3.1;this.sun.position.set(-50,30,15);this.fill.intensity=1.45;this.scene.background=new T.Color('#d2c4a8');}else{this.sun.color.set('#ffead0');this.sun.intensity=2.6;this.sun.position.set(-32,62,28);this.fill.intensity=1.8;this.scene.background=new T.Color('#bdd1d5');}if(grey){this.sun.color.set('#dbe6ea');this.sun.intensity=weather==='storm'?.45:1.1;this.fill.intensity=weather==='storm'?1.15:2.1;this.scene.background=new T.Color(weather==='storm'?'#748991':'#afc3c9');}this.renderer.toneMappingExposure=1.02;this.world.environment.golden.value=light==='golden'?1:0;this.world.environment.sunDirection.value.copy(this.sun.position).normalize();this.world.environment.setWeather(light==='overcast'&&weather==='clear'?'overcast':weather);this.world.forest.bake(this.sun,this.fill);if(this.view!=='studio')this.scene.fog=new T.FogExp2(this.scene.background as T.Color,weather==='storm'?.008:.0032);}
 setWeather(weather:Weather){this.weather=weather;this.setLight(this.currentLight);}
 setClip(clip:Clip){this.clip=clip;}
 setOreRemaining(percent:number){this.world.setOreRemaining(percent);this.world.models.get('mine')!.getObjectByName('ore')!.visible=percent>0;if(this.asset==='mine')this.preview?.getObjectByName('ore')?.traverse(o=>o.visible=percent>0);this.renderer.shadowMap.needsUpdate=true;}
 setQuality(q:string){this.quality=q;this.renderer.setPixelRatio(q==='high'?1.6:1);this.renderer.shadowMap.enabled=q==='high';this.world.grass.visible=q==='high';}
 setMotion(enabled:boolean){this.motion=enabled;this.controls.autoRotate=false;}
 setWireframe(enabled:boolean){this.wireframe=enabled;this.applyWireframe();}
 private applyWireframe(){this.scene.traverse(o=>{if(o instanceof T.Mesh&&o.material instanceof T.MeshStandardMaterial)o.material.wireframe=this.wireframe;});}
 capture(){this.renderer.render(this.scene,this.camera);const a=document.createElement('a');a.href=this.renderer.domElement.toDataURL('image/png');a.download=`meridian-${this.view==='studio'?this.asset:this.view}.png`;a.click();}
 private tick=(now:number)=>{const cpuStart=performance.now();const dt=this.last?Math.min((now-this.last)/1000,.05):.016;this.last=now;if(this.motion)this.elapsed+=dt;const t=this.elapsed;
 if(this.targetPos&&this.targetLook){const blend=1-Math.exp(-dt*5);this.camera.position.lerp(this.targetPos,blend);this.controls.target.lerp(this.targetLook,blend);if(this.camera.position.distanceTo(this.targetPos)<.05){this.targetPos=null;this.targetLook=null;}}
 if(this.keySet.size&&this.view!=='studio'){const forward=new T.Vector3();this.camera.getWorldDirection(forward);forward.y=0;forward.normalize();const side=new T.Vector3().crossVectors(forward,new T.Vector3(0,1,0));const v=new T.Vector3();if(this.keySet.has('w')||this.keySet.has('arrowup'))v.add(forward);if(this.keySet.has('s')||this.keySet.has('arrowdown'))v.sub(forward);if(this.keySet.has('a')||this.keySet.has('arrowleft'))v.sub(side);if(this.keySet.has('d')||this.keySet.has('arrowright'))v.add(side);v.multiplyScalar(dt*20);this.camera.position.add(v);this.controls.target.add(v);}
 this.controls.target.x=T.MathUtils.clamp(this.controls.target.x,-65,65);this.controls.target.z=T.MathUtils.clamp(this.controls.target.z,-65,65);this.controls.update(dt);
 setFoliageTime(t,this.world.environment.wind.value);
 if(this.view!=='studio'){this.world.update(t);this.world.forest.update(this.camera,this.renderer.domElement.height);this.world.environment.update(t,this.camera);}else if(this.preview)animateAsset(this.preview,t,this.clip);
 const ps=this.smoke.geometry.attributes.position;const chimneys=this.world.layout.buildings.filter(p=>p.kind==='house').slice(0,3);for(let i=0;i<ps.count;i++){const phase=(t*.25+i/12)%1,{x,z,y}=chimneys[i%3];ps.setXYZ(i,x-.8+phase*2+Math.sin(i*7)*.15,y+4.1+phase*4,z-.65+phase*.65);}ps.needsUpdate=true;
 this.birds.children.forEach((b,i)=>{const a=t*.08+i*.45;b.position.set(19+Math.cos(a)*16,16+Math.sin(a*.8)*2+i*.3,-7+Math.sin(a)*12);b.rotation.y=-a;b.rotation.z=Math.sin(t*.7+i)*.08;for(const s of [-1,1]){const w=b.getObjectByName(`wing${s}`);if(w)w.rotation.z=s*Math.sin(t*3.6+i)*.40;}});
 if(this.lastShadow<0||this.view==='studio'||t-this.lastShadow>1/30){this.renderer.shadowMap.needsUpdate=true;this.lastShadow=t;}this.renderer.render(this.scene,this.camera);this.cpuMs=this.cpuMs*.9+(performance.now()-cpuStart)*.1;if(this.first){this.first=false;this.onReady();}
 this.frames++;if(now-this.sample>1000){const fps=Math.round(this.frames*1000/(now-this.sample));this.onMetrics({fps,frameMs:Math.round(10000/fps)/10,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,geometries:this.renderer.info.memory.geometries,textures:this.renderer.info.memory.textures,backend:'WebGL 2',cpuMs:Math.round(this.cpuMs*10)/10,pixels:this.renderer.domElement.width*this.renderer.domElement.height,...this.world.stats});this.frames=0;this.sample=now;}
 this.frame=requestAnimationFrame(this.tick);
 };
 dispose(){cancelAnimationFrame(this.frame);this.world.forest.dispose();this.disposer.forEach(fn=>fn());this.controls.dispose();const gs=new Set<T.BufferGeometry>(),ms=new Set<T.Material>(),textures=new Set<T.Texture>();const collect=(o:T.Object3D)=>{if(o instanceof T.Mesh||o instanceof T.Points){gs.add(o.geometry);(Array.isArray(o.material)?o.material:[o.material]).forEach((m:T.Material)=>{ms.add(m);Object.values(m).forEach(v=>{if(v instanceof T.Texture)textures.add(v);});});}};this.scene.traverse(collect);this.world.models.forEach(m=>m.traverse(collect));gs.forEach(g=>g.dispose());ms.forEach(m=>m.dispose());textures.forEach(t=>t.dispose());this.renderer.dispose();this.renderer.domElement.remove();}
}
export {assetInfo};
