import {z} from 'zod';
import type {ResourceKind, Resources} from '../../protocol/src/index';

export const CONTENT_VERSION = 5;
const bundle = z.object({
  provisions: z.number().int().nonnegative(),
  timber: z.number().int().nonnegative(),
  coin: z.number().int().nonnegative(),
  metal: z.number().int().nonnegative(),
});
const unitSchema = z.object({
  id: z.string(),
  name: z.string(),
  age: z.number().int().min(1).max(4),
  trainedAt: z.string(),
  cost: bundle,
  trainTicks: z.number().int().positive(),
  population: z.number().int().positive(),
  hp: z.number().int().positive(),
  speed: z.number().int().positive(),
  range: z.number().int().nonnegative(),
  damage: z.number().int().positive(),
  cooldown: z.number().int().positive(),
  tags: z.array(z.string()),
  model: z.string(),
});
export type UnitDefinition = z.infer<typeof unitSchema>;
const buildingSchema = z.object({
  id: z.string(),
  name: z.string(),
  age: z.number().int().min(1).max(4),
  cost: bundle,
  buildTicks: z.number().int().positive(),
  hp: z.number().int().positive(),
  population: z.number().int().nonnegative(),
  production: z.array(z.string()),
  model: z.string(),
  footprint: z.tuple([z.number().positive(), z.number().positive()]),
});
export type BuildingDefinition = z.infer<typeof buildingSchema>;
const cost = (provisions = 0, timber = 0, coin = 0, metal = 0): Resources => ({provisions, timber, coin, metal});

export const units = unitSchema.array().parse([
  {
    id: 'worker',
    name: 'Frontier Worker',
    age: 1,
    trainedAt: 'hall',
    cost: cost(5000),
    trainTicks: 300,
    population: 1,
    hp: 70,
    speed: 42,
    range: 0,
    damage: 4,
    cooldown: 30,
    tags: ['worker'],
    model: 'villager',
  },
  {
    id: 'explorer',
    name: 'Frontier Explorer',
    age: 1,
    trainedAt: 'hall',
    cost: cost(0),
    trainTicks: 1,
    population: 1,
    hp: 180,
    speed: 52,
    range: 760,
    damage: 12,
    cooldown: 28,
    tags: ['explorer', 'ranged'],
    model: 'explorer',
  },
  {
    id: 'militia',
    name: 'Militia',
    age: 1,
    trainedAt: 'barracks',
    cost: cost(6000, 2500),
    trainTicks: 360,
    population: 1,
    hp: 105,
    speed: 40,
    range: 0,
    damage: 11,
    cooldown: 24,
    tags: ['infantry', 'melee'],
    model: 'militia',
  },
  {
    id: 'spearman',
    name: 'Levy Spearman',
    age: 1,
    trainedAt: 'barracks',
    cost: cost(5000, 3500),
    trainTicks: 380,
    population: 1,
    hp: 115,
    speed: 38,
    range: 0,
    damage: 15,
    cooldown: 28,
    tags: ['infantry', 'anti-cavalry'],
    model: 'spearman',
  },
  {
    id: 'archer',
    name: 'Bow Archer',
    age: 1,
    trainedAt: 'barracks',
    cost: cost(4500, 5000),
    trainTicks: 400,
    population: 1,
    hp: 75,
    speed: 40,
    range: 1280,
    damage: 10,
    cooldown: 32,
    tags: ['infantry', 'ranged'],
    model: 'archer',
  },
  {
    id: 'swordsman',
    name: 'Swordsman',
    age: 2,
    trainedAt: 'barracks',
    cost: cost(6500, 0, 0, 3000),
    trainTicks: 460,
    population: 1,
    hp: 145,
    speed: 38,
    range: 0,
    damage: 18,
    cooldown: 25,
    tags: ['infantry', 'melee'],
    model: 'swordsman',
  },
  {
    id: 'shieldBearer',
    name: 'Shield Bearer',
    age: 2,
    trainedAt: 'barracks',
    cost: cost(6000, 3500, 0, 2500),
    trainTicks: 480,
    population: 1,
    hp: 175,
    speed: 34,
    range: 0,
    damage: 12,
    cooldown: 27,
    tags: ['infantry', 'armored'],
    model: 'shieldBearer',
  },
  {
    id: 'lightRider',
    name: 'Light Rider',
    age: 2,
    trainedAt: 'stable',
    cost: cost(9000, 0, 4000),
    trainTicks: 560,
    population: 2,
    hp: 190,
    speed: 65,
    range: 0,
    damage: 22,
    cooldown: 30,
    tags: ['cavalry', 'melee'],
    model: 'lightRider',
  },
  {
    id: 'mountedScout',
    name: 'Mounted Scout',
    age: 2,
    trainedAt: 'stable',
    cost: cost(7000, 0, 3000),
    trainTicks: 480,
    population: 1,
    hp: 130,
    speed: 74,
    range: 0,
    damage: 8,
    cooldown: 30,
    tags: ['cavalry', 'scout'],
    model: 'mountedScout',
  },
  {
    id: 'ramWagon',
    name: 'Ram Wagon',
    age: 2,
    trainedAt: 'workshop',
    cost: cost(0, 11000, 0, 5000),
    trainTicks: 700,
    population: 3,
    hp: 420,
    speed: 25,
    range: 0,
    damage: 45,
    cooldown: 45,
    tags: ['siege'],
    model: 'ramWagon',
  },
  {
    id: 'pikeman',
    name: 'Long Pike',
    age: 3,
    trainedAt: 'barracks',
    cost: cost(6500, 4000, 0, 2500),
    trainTicks: 460,
    population: 1,
    hp: 150,
    speed: 36,
    range: 0,
    damage: 25,
    cooldown: 28,
    tags: ['infantry', 'anti-cavalry'],
    model: 'pikeman',
  },
  {
    id: 'crossbow',
    name: 'Crossbow Guard',
    age: 3,
    trainedAt: 'barracks',
    cost: cost(5500, 5500, 1500),
    trainTicks: 500,
    population: 1,
    hp: 100,
    speed: 37,
    range: 1450,
    damage: 18,
    cooldown: 38,
    tags: ['infantry', 'ranged'],
    model: 'crossbow',
  },
  {
    id: 'cavalry',
    name: 'League Lancer',
    age: 3,
    trainedAt: 'stable',
    cost: cost(10000, 0, 6500, 2500),
    trainTicks: 650,
    population: 2,
    hp: 255,
    speed: 62,
    range: 0,
    damage: 32,
    cooldown: 34,
    tags: ['cavalry', 'melee'],
    model: 'cavalry',
  },
  {
    id: 'cannon',
    name: 'Field Cannon',
    age: 3,
    trainedAt: 'workshop',
    cost: cost(0, 8000, 8000, 9000),
    trainTicks: 820,
    population: 4,
    hp: 240,
    speed: 23,
    range: 2050,
    damage: 42,
    cooldown: 70,
    tags: ['artillery', 'ranged'],
    model: 'cannon',
  },
  {
    id: 'veteranRifle',
    name: 'Veteran Rifle',
    age: 4,
    trainedAt: 'barracks',
    cost: cost(7000, 0, 6500, 2500),
    trainTicks: 520,
    population: 1,
    hp: 145,
    speed: 39,
    range: 1750,
    damage: 24,
    cooldown: 34,
    tags: ['infantry', 'ranged'],
    model: 'veteranRifle',
  },
  {
    id: 'grenadier',
    name: 'Grenadier',
    age: 4,
    trainedAt: 'arsenal',
    cost: cost(8500, 0, 4500, 5000),
    trainTicks: 600,
    population: 2,
    hp: 175,
    speed: 34,
    range: 1300,
    damage: 34,
    cooldown: 48,
    tags: ['infantry', 'blast'],
    model: 'grenadier',
  },
  {
    id: 'marksman',
    name: 'Marksman',
    age: 4,
    trainedAt: 'archery',
    cost: cost(6000, 0, 7500, 2000),
    trainTicks: 560,
    population: 1,
    hp: 105,
    speed: 38,
    range: 2150,
    damage: 30,
    cooldown: 46,
    tags: ['infantry', 'ranged'],
    model: 'marksman',
  },
  {
    id: 'skirmisher',
    name: 'Skirmisher',
    age: 4,
    trainedAt: 'archery',
    cost: cost(6500, 2000, 5000),
    trainTicks: 500,
    population: 1,
    hp: 120,
    speed: 43,
    range: 1650,
    damage: 20,
    cooldown: 30,
    tags: ['infantry', 'ranged'],
    model: 'skirmisher',
  },
  {
    id: 'dragoon',
    name: 'Dragoon',
    age: 4,
    trainedAt: 'stable',
    cost: cost(9000, 0, 8000, 3000),
    trainTicks: 650,
    population: 2,
    hp: 220,
    speed: 68,
    range: 1550,
    damage: 25,
    cooldown: 36,
    tags: ['cavalry', 'ranged'],
    model: 'dragoon',
  },
  {
    id: 'cuirassRider',
    name: 'Cuirass Rider',
    age: 4,
    trainedAt: 'stable',
    cost: cost(12000, 0, 9000, 6000),
    trainTicks: 760,
    population: 3,
    hp: 360,
    speed: 58,
    range: 0,
    damage: 42,
    cooldown: 36,
    tags: ['cavalry', 'armored', 'melee'],
    model: 'cuirassRider',
  },
  {
    id: 'howitzer',
    name: 'Howitzer',
    age: 4,
    trainedAt: 'factory',
    cost: cost(0, 9000, 10000, 14000),
    trainTicks: 900,
    population: 5,
    hp: 280,
    speed: 20,
    range: 2500,
    damage: 58,
    cooldown: 82,
    tags: ['artillery', 'ranged'],
    model: 'howitzer',
  },
  {
    id: 'mortar',
    name: 'Mortar',
    age: 4,
    trainedAt: 'factory',
    cost: cost(0, 7000, 9000, 12000),
    trainTicks: 840,
    population: 4,
    hp: 220,
    speed: 18,
    range: 2850,
    damage: 70,
    cooldown: 95,
    tags: ['artillery', 'siege', 'ranged'],
    model: 'mortar',
  },
  {
    id: 'rocketCart',
    name: 'Rocket Cart',
    age: 4,
    trainedAt: 'factory',
    cost: cost(0, 8000, 12000, 12000),
    trainTicks: 920,
    population: 5,
    hp: 230,
    speed: 22,
    range: 2350,
    damage: 52,
    cooldown: 74,
    tags: ['artillery', 'blast', 'ranged'],
    model: 'rocketCart',
  },
  {
    id: 'medic',
    name: 'Field Medic',
    age: 3,
    trainedAt: 'academy',
    cost: cost(7000, 0, 5000),
    trainTicks: 500,
    population: 1,
    hp: 95,
    speed: 42,
    range: 0,
    damage: 3,
    cooldown: 40,
    tags: ['support'],
    model: 'medic',
  },
  {
    id: 'engineer',
    name: 'Engineer',
    age: 4,
    trainedAt: 'academy',
    cost: cost(7500, 3500, 4000, 2000),
    trainTicks: 520,
    population: 1,
    hp: 105,
    speed: 40,
    range: 900,
    damage: 12,
    cooldown: 34,
    tags: ['support', 'ranged'],
    model: 'engineer',
  },
  {
    id: 'commander',
    name: 'Field Commander',
    age: 4,
    trainedAt: 'academy',
    cost: cost(10000, 0, 10000, 4000),
    trainTicks: 800,
    population: 2,
    hp: 260,
    speed: 42,
    range: 1100,
    damage: 28,
    cooldown: 35,
    tags: ['infantry', 'support', 'ranged'],
    model: 'commander',
  },
]);
export const unitById = new Map(units.map((x) => [x.id, x]));

export const buildings = buildingSchema.array().parse([
  {
    id: 'hall',
    name: 'Charter Hall',
    age: 1,
    cost: cost(),
    buildTicks: 1,
    hp: 1600,
    population: 10,
    production: ['worker'],
    model: 'hall',
    footprint: [6.1, 4.6],
  },
  {
    id: 'house',
    name: 'Harbor Residence',
    age: 1,
    cost: cost(0, 9000),
    buildTicks: 420,
    hp: 500,
    population: 10,
    production: [],
    model: 'house',
    footprint: [2.9, 1.95],
  },
  {
    id: 'lumberPost',
    name: 'Lumber Post',
    age: 1,
    cost: cost(0, 8000),
    buildTicks: 360,
    hp: 450,
    population: 0,
    production: [],
    model: 'lumberPost',
    footprint: [2.8, 2],
  },
  {
    id: 'miningPost',
    name: 'Mining Post',
    age: 2,
    cost: cost(0, 7000, 0, 2500),
    buildTicks: 400,
    hp: 470,
    population: 0,
    production: [],
    model: 'miningPost',
    footprint: [2.9, 2.2],
  },
  {
    id: 'silo',
    name: 'Grain Silo',
    age: 2,
    cost: cost(0, 7000),
    buildTicks: 380,
    hp: 450,
    population: 0,
    production: [],
    model: 'silo',
    footprint: [2.8, 2.3],
  },
  {
    id: 'barracks',
    name: 'Barracks',
    age: 1,
    cost: cost(0, 14000),
    buildTicks: 600,
    hp: 750,
    population: 0,
    production: ['militia', 'spearman', 'archer', 'swordsman', 'shieldBearer', 'pikeman', 'crossbow'],
    model: 'barracks',
    footprint: [3.9, 4.9],
  },
  {
    id: 'stable',
    name: 'Stable',
    age: 2,
    cost: cost(0, 15000, 0, 2000),
    buildTicks: 650,
    hp: 720,
    population: 0,
    production: ['lightRider', 'mountedScout', 'cavalry'],
    model: 'stable',
    footprint: [3.9, 4.9],
  },
  {
    id: 'workshop',
    name: 'Artillery Works',
    age: 3,
    cost: cost(0, 17000, 0, 7000),
    buildTicks: 800,
    hp: 850,
    population: 0,
    production: ['ramWagon', 'cannon'],
    model: 'workshop',
    footprint: [3.9, 4.9],
  },
  {
    id: 'market',
    name: 'Exchange House',
    age: 2,
    cost: cost(0, 12000),
    buildTicks: 500,
    hp: 620,
    population: 0,
    production: [],
    model: 'market',
    footprint: [3, 3.5],
  },
  {
    id: 'tradePost',
    name: 'Trade Post',
    age: 2,
    cost: cost(0, 9000, 3000),
    buildTicks: 500,
    hp: 600,
    population: 0,
    production: [],
    model: 'tradePost',
    footprint: [3.2, 3.2],
  },
  {
    id: 'tower',
    name: 'Coastal Watch',
    age: 2,
    cost: cost(0, 9000, 0, 5000),
    buildTicks: 550,
    hp: 900,
    population: 0,
    production: [],
    model: 'tower',
    footprint: [3, 3],
  },
  {
    id: 'wall',
    name: 'Wall',
    age: 2,
    cost: cost(0, 2500, 0, 1000),
    buildTicks: 180,
    hp: 700,
    population: 0,
    production: [],
    model: 'wall',
    footprint: [3.2, 1.3],
  },
  {
    id: 'gate',
    name: 'Gate',
    age: 2,
    cost: cost(0, 4500, 0, 2000),
    buildTicks: 300,
    hp: 900,
    population: 0,
    production: [],
    model: 'gate',
    footprint: [4.2, 2.2],
  },
  {
    id: 'fort',
    name: 'Aurelian Fort',
    age: 3,
    cost: cost(0, 30000, 10000, 18000),
    buildTicks: 1200,
    hp: 2600,
    population: 0,
    production: ['militia', 'spearman', 'swordsman', 'archer', 'crossbow'],
    model: 'fort',
    footprint: [6.8, 6.8],
  },
  {
    id: 'farm',
    name: 'Farm',
    age: 2,
    cost: cost(0, 6500),
    buildTicks: 350,
    hp: 350,
    population: 0,
    production: [],
    model: 'farm',
    footprint: [4.4, 6.2],
  },
  {
    id: 'archery',
    name: 'Archery Range',
    age: 2,
    cost: cost(0, 13000),
    buildTicks: 580,
    hp: 700,
    population: 0,
    production: ['archer', 'crossbow', 'marksman', 'skirmisher'],
    model: 'archery',
    footprint: [4.2, 4.8],
  },
  {
    id: 'dock',
    name: 'Harbor Dock',
    age: 2,
    cost: cost(0, 17000, 0, 3000),
    buildTicks: 720,
    hp: 1000,
    population: 0,
    production: [],
    model: 'dock',
    footprint: [5.2, 7.2],
  },
  {
    id: 'arsenal',
    name: 'Arsenal',
    age: 3,
    cost: cost(0, 15000, 3000, 7000),
    buildTicks: 700,
    hp: 820,
    population: 0,
    production: ['grenadier'],
    model: 'arsenal',
    footprint: [4.4, 4.4],
  },
  {
    id: 'academy',
    name: 'Academy',
    age: 3,
    cost: cost(0, 14000, 7000, 3000),
    buildTicks: 680,
    hp: 760,
    population: 0,
    production: ['medic', 'engineer', 'commander'],
    model: 'academy',
    footprint: [4.3, 4.8],
  },
  {
    id: 'temple',
    name: 'Civic Sanctuary',
    age: 2,
    cost: cost(0, 12000, 5000),
    buildTicks: 620,
    hp: 800,
    population: 0,
    production: [],
    model: 'temple',
    footprint: [4.2, 4.2],
  },
  {
    id: 'embassy',
    name: 'Alliance Embassy',
    age: 3,
    cost: cost(0, 13000, 8000),
    buildTicks: 650,
    hp: 780,
    population: 0,
    production: [],
    model: 'embassy',
    footprint: [4.5, 4.2],
  },
  {
    id: 'mercenaryHall',
    name: 'Contract Hall',
    age: 3,
    cost: cost(0, 15000, 10000),
    buildTicks: 720,
    hp: 850,
    population: 0,
    production: [],
    model: 'mercenaryHall',
    footprint: [5.0, 4.8],
  },
  {
    id: 'factory',
    name: 'Engine Factory',
    age: 4,
    cost: cost(0, 30000, 16000, 22000),
    buildTicks: 1200,
    hp: 1300,
    population: 0,
    production: ['howitzer', 'mortar', 'rocketCart'],
    model: 'factory',
    footprint: [6.2, 5.2],
  },
  {
    id: 'estate',
    name: 'Orchard Estate',
    age: 3,
    cost: cost(0, 11000, 3000),
    buildTicks: 560,
    hp: 600,
    population: 0,
    production: [],
    model: 'estate',
    footprint: [4.4, 6.2],
  },
  {
    id: 'fishery',
    name: 'Shore Fishery',
    age: 1,
    cost: cost(0, 9000),
    buildTicks: 440,
    hp: 550,
    population: 0,
    production: [],
    model: 'fishery',
    footprint: [4.2, 4.8],
  },
  {
    id: 'landmark',
    name: 'Meridian Beacon',
    age: 3,
    cost: cost(0, 22000, 16000, 12000),
    buildTicks: 1000,
    hp: 1800,
    population: 0,
    production: [],
    model: 'landmark',
    footprint: [5.5, 5.5],
  },
]);
export const buildingById = new Map(buildings.map((x) => [x.id, x]));
export const resourceKinds: ResourceKind[] = ['provisions', 'timber', 'coin', 'metal'];
const dispatchSchema = z.object({
  id: z.string(),
  name: z.string(),
  age: z.number().int().min(1).max(4),
  tokenCost: z.number().int().positive(),
  departureTicks: z.number().int().positive(),
  arrivalTicks: z.number().int().positive(),
  resources: bundle,
  units: z.array(z.object({unitId: z.string(), count: z.number().int().positive()})),
});
export type DispatchDefinition = z.infer<typeof dispatchSchema>;
const charter = (index: number, name: string, age: number, resources: Resources, unitId?: string, count = 0) => ({
  id: `charter-${index}`,
  name,
  age,
  tokenCost: age >= 3 ? 2 : 1,
  departureTicks: 100,
  arrivalTicks: 400 + age * 100,
  resources,
  units: unitId ? [{unitId, count}] : [],
});
export const dispatches = dispatchSchema
  .array()
  .parse([
    charter(1, 'Provision Convoy', 1, cost(15000)),
    charter(2, 'Timber Charter', 1, cost(0, 15000)),
    charter(3, 'Coin Credit', 1, cost(0, 0, 12000)),
    charter(4, 'Metalwrights', 1, cost(0, 0, 0, 10000)),
    charter(5, 'Worker Party', 1, cost(), 'worker', 2),
    charter(6, 'Militia Detail', 1, cost(), 'militia', 3),
    charter(7, 'Frontier Supplies', 1, cost(8000, 8000)),
    charter(8, 'Spear Escort', 1, cost(), 'spearman', 3),
    charter(9, 'Bow Detachment', 1, cost(), 'archer', 3),
    charter(10, 'Surveyor Supplies', 1, cost(4000, 5000, 4000)),
    charter(11, 'Settlement Stores', 2, cost(20000, 12000)),
    charter(12, 'Sword Company', 2, cost(), 'swordsman', 3),
    charter(13, 'Shield Escort', 2, cost(), 'shieldBearer', 3),
    charter(14, 'Light Riders', 2, cost(), 'lightRider', 2),
    charter(15, 'Mounted Reconnaissance', 2, cost(), 'mountedScout', 2),
    charter(16, 'Ram Reinforcement', 2, cost(), 'ramWagon', 1),
    charter(17, 'Guild Materials', 2, cost(0, 16000, 8000, 8000)),
    charter(18, 'Settler Expedition', 2, cost(6000), 'worker', 3),
    charter(19, 'Pike Reserve', 3, cost(), 'pikeman', 5),
    charter(20, 'Crossbow Reserve', 3, cost(), 'crossbow', 5),
    charter(21, 'Lancer Squadron', 3, cost(), 'cavalry', 3),
    charter(22, 'Field Battery', 3, cost(), 'cannon', 1),
    charter(23, 'Fortification Stores', 3, cost(0, 22000, 0, 18000)),
    charter(24, 'League Treasury', 3, cost(10000, 0, 22000, 8000)),
  ]);
for (const card of dispatches) {
  for (const delivery of card.units) {
    const definition = unitById.get(delivery.unitId);
    if (!definition || definition.age > card.age) throw new Error(`Invalid Dispatch unit: ${card.id}`);
  }
}
export function dispatchDescription(card: DispatchDefinition) {
  return [
    ...resourceKinds.filter((kind) => card.resources[kind] > 0).map((kind) => `${card.resources[kind] / 100} ${kind}`),
    ...card.units.map((delivery) => `${delivery.count} ${unitById.get(delivery.unitId)!.name}`),
  ].join(' · ');
}

const councilModifierSchema = z.object({
  description: z.string(),
  gather: z.number().int().default(10000),
  production: z.number().int().default(10000),
  construction: z.number().int().default(10000),
  carry: z.number().int().default(10000),
  military: z.number().int().default(10000),
  artillery: z.number().int().default(10000),
  buildingDamage: z.number().int().default(10000),
  market: z.number().int().default(10000),
});
export const councilModifiers = z.record(z.string(), councilModifierSchema).parse({
  gather: {description: 'Workers gather 25% faster.', gather: 12500},
  military: {description: 'Military units deal 10% more damage.', military: 11000},
  market: {description: 'Markets produce 20% more Coin.', market: 12000},
  production: {description: 'Unit training progresses 25% faster.', production: 12500},
  defense: {description: 'Buildings take 15% less damage.', buildingDamage: 8500},
  'industrial-production': {
    description: 'Unit training and construction progress twice as fast.',
    production: 20000,
    construction: 20000,
  },
  'industrial-logistics': {description: 'Workers carry 50% more resources.', carry: 15000},
  'industrial-military': {description: 'Artillery deals 20% more damage.', artillery: 12000},
});
export type CouncilStat = Exclude<keyof z.infer<typeof councilModifierSchema>, 'description'>;
export function councilRate(modifiers: string[], stat: CouncilStat) {
  return (
    10000 + [...new Set(modifiers)].reduce((total, id) => total + ((councilModifiers[id]?.[stat] ?? 10000) - 10000), 0)
  );
}
export const advancements = z
  .array(z.object({age: z.number().int().min(2).max(4), ticks: z.number().int().positive(), cost: bundle}))
  .parse([
    {age: 2, ticks: 600, cost: cost(50000, 30000)},
    {age: 3, ticks: 600, cost: cost(70000, 40000, 25000, 15000)},
    {age: 4, ticks: 600, cost: cost(90000, 60000, 50000, 40000)},
  ]);
export const councilChoices = z
  .array(
    z.object({
      id: z.string(),
      age: z.number().int().min(2).max(4),
      name: z.string(),
      delivery: bundle,
      modifier: z.string(),
    }),
  )
  .parse([
    {
      id: 'harvest-council',
      age: 2,
      name: 'Harvest Council',
      delivery: {provisions: 12000, timber: 8000, coin: 0, metal: 0},
      modifier: 'gather',
    },
    {
      id: 'charter-guard',
      age: 2,
      name: 'Charter Guard',
      delivery: {provisions: 5000, timber: 0, coin: 5000, metal: 5000},
      modifier: 'military',
    },
    {
      id: 'coastal-trade',
      age: 2,
      name: 'Coastal Trade',
      delivery: {provisions: 0, timber: 6000, coin: 12000, metal: 0},
      modifier: 'market',
    },
    {
      id: 'guild-council',
      age: 3,
      name: 'Guild Council',
      delivery: {provisions: 9000, timber: 9000, coin: 9000, metal: 0},
      modifier: 'production',
    },
    {
      id: 'bastion-council',
      age: 3,
      name: 'Bastion Council',
      delivery: {provisions: 0, timber: 8000, coin: 0, metal: 14000},
      modifier: 'defense',
    },
    {
      id: 'field-command',
      age: 3,
      name: 'Field Command',
      delivery: {provisions: 8000, timber: 0, coin: 8000, metal: 8000},
      modifier: 'military',
    },
    {
      id: 'industrial-guilds',
      age: 4,
      name: 'Industrial Guilds',
      delivery: {provisions: 10000, timber: 12000, coin: 14000, metal: 10000},
      modifier: 'industrial-production',
    },
    {
      id: 'modern-logistics',
      age: 4,
      name: 'Industrial Logistics',
      delivery: {provisions: 18000, timber: 10000, coin: 8000, metal: 8000},
      modifier: 'industrial-logistics',
    },
    {
      id: 'artillery-board',
      age: 4,
      name: 'Artillery Board',
      delivery: {provisions: 6000, timber: 6000, coin: 12000, metal: 18000},
      modifier: 'industrial-military',
    },
  ]);
for (const choice of councilChoices)
  if (!councilModifiers[choice.modifier]) throw new Error(`Unknown council modifier: ${choice.id}`);
export function sightFor(kind: string, age = 1) {
  const ranges: Record<string, number> = {
    worker: 13,
    explorer: 30,
    mountedScout: 32,
    cavalry: 22,
    lightRider: 23,
    archer: 20,
    crossbow: 22,
    cannon: 25,
    veteranRifle: 22,
    grenadier: 20,
    marksman: 27,
    skirmisher: 23,
    dragoon: 25,
    cuirassRider: 22,
    howitzer: 28,
    mortar: 25,
    rocketCart: 27,
    hall: 24,
    fort: 30,
    tower: 32,
    house: 11,
    barracks: 16,
    stable: 17,
    workshop: 17,
    market: 15,
    tradePost: 19,
    lumberPost: 11,
    miningPost: 11,
    silo: 10,
    farm: 9,
    archery: 16,
    dock: 20,
    arsenal: 16,
    academy: 18,
    temple: 17,
    embassy: 18,
    mercenaryHall: 17,
    factory: 19,
    estate: 11,
    fishery: 14,
    landmark: 30,
    wall: 6,
    gate: 10,
    sheep: 6,
  };
  return (ranges[kind] ?? 16) + (kind === 'hall' || kind === 'fort' || kind === 'tower' ? (age - 1) * 3 : 0);
}
export function garrisonCapacity(kind: string, age: number) {
  return kind === 'hall' ? 10 + (age - 1) * 5 : kind === 'fort' ? 20 + (age - 1) * 5 : 0;
}
