import {eras,unlockAge,retireAge} from './ages';
// Gameplay intent is documented separately from the visual sandbox implementation.
export const roles:Record<string,string>={
 hall:'The settlement’s civic center. Trains workers, receives gathered resources and advances the civilization’s age. Its assembly hall and administrative wings grow from a communal shelter into a civic complex.',
 house:'Population housing. Raises the capacity for workers and military units; it does not train troops. Wattle huts give way to masonry homes, industrial residences and taller brick residences.',
 market:'The trading exchange. Converts surplus resources and researches economic improvements. Open stalls and a central counting house distinguish it from military production buildings.',
 tower:'A compact defensive observation post. Controls a small area and protects workers; it cannot replace a fortified stronghold. Later versions gain stronger masonry and firearm-era observation galleries.',
 lumberPost:'A local timber collection point. Shortens workers’ trips from remote forests and supports lumber upgrades. Open storage bays keep stacked logs accessible to carriers.',
 miningPost:'An open ore and stone collection point with sorting equipment. Supports mining efficiency and receives material from nearby deposits; it is not itself a source of ore.',
 silo:'Grain storage for surrounding farms. Receives harvested food and supports farming improvements. Masonry grain bins become paired industrial metal silos with a loading ladder.',
 stable:'A mounted-unit training compound. Houses scout mounts, light cavalry and later armored riders. Its stall block, hayloft, water trough and enclosed exercise yard serve different parts of horse training.',
 militia:'An early citizen infantry unit trained at the Stone Age barracks. Carries a wooden club with light clothing and no heavy armor. Researching forged blades from the Classical Age upgrades this unit line to swordsmen.',
 barracks:'The infantry training compound, available from the Stone Age. Trains militia, whose unit line upgrades to swordsmen after forged-blade research in the Classical Age, then supports later infantry. Dormitories and an armory open onto a courtyard with training dummies.',
 archery:'A specialist ranged-unit school. Produces bowmen and later crossbow troops, with a fletcher’s workshop beside long target lanes. Firearm recruitment moves to the barracks instead of pretending a modern bow range is a gun factory.',
 workshop:'A heavy-weapon production yard. Builds artillery and supports siege engineering. A foundry, machining benches and an open assembly court provide room for crews and gun carriages.',
 dock:'The naval construction and repair site. Produces fishing, trading, transport and combat vessels as their technologies unlock. Its loading crane and broad pier support larger ships than a shore fishery.',
 tradePost:'A route-side commercial outpost. Supports trade wagons and income from controlled routes. Cargo stacks and a small counting office make its logistical purpose visible.',
 mercenaryHall:'A contract recruitment compound. Hires specialist soldiers in exchange for resources. Its contract office and mustering yard support a smaller professional force rather than mass infantry training.',
 embassy:'A diplomatic headquarters. Enables alliance units and diplomatic upgrades. A reception hall and paired ceremonial standards distinguish it from a barracks.',
 arsenal:'A protected equipment store and military research site. Improves weapons and armor rather than directly training ordinary troops. Reinforced storage and guard towers protect valuable supplies.',
 academy:'An advanced research campus. Enables higher-tier military and economic technologies. A library, lecture wing and laboratory surround a small open court.',
 temple:'A civic and spiritual sanctuary. Supports healing and cultural research. Its elevated platform, colonnade and dome make it a landmark within the settlement.',
 factory:'An industrial production complex. Builds mechanized equipment and supports advanced manufacturing. Machine halls, tall exhaust stacks, tanks and a loading yard replace the smaller artisan workshop.',
 wall:'A defensive curtain segment. Blocks land movement and connects to gates and towers. It creates a barrier rather than producing units or resources.',
 gate:'A controlled opening through a defensive wall. Admits friendly traffic while maintaining a fortified entrance. Twin towers protect the passage and its portcullis.',
 fort:'A castle-like regional stronghold. Supports garrison defense, siege resistance and elite military control. The Medieval version has a tall inner keep, curtain walls, corner towers and a gatehouse. Industrial artillery doctrine replaces it with broad, low, sloping bastions and protected gun platforms.',
 landmark:'A major civic monument. Represents high investment and a potential scenario objective. Its stepped foundation and elevated beacon give it a silhouette distinct from an ordinary sanctuary.',
 farm:'A renewable grain field. Workers travel between rows to cultivate and harvest food, then deliver it to a silo or civic center. The entire crop footprint is reserved against rocks and other scenery.',
 estate:'A larger managed agricultural property. Combines cultivated land with an estate house and supports later economic development. It occupies more space than a basic farm.',
 fishery:'A small shoreline food-gathering facility. Supports local net fishing and receiving the catch. Its short working platform serves shore workers rather than constructing warships.',
 infantry:'A line firearm soldier trained at the barracks. Fires aimed shots before reloading; effective in organized ranged formations but vulnerable when isolated. Its shako, crossbelts and long musket identify the standard firearm battle line.',
 spearman:'An inexpensive early infantry unit. Uses a long thrusting spear to keep mounted enemies at a distance. A simple spear, open helmet and short tunic remain readable from a distance.',
 swordsman:'A close-combat infantry soldier carrying a sword and shield. Closes the distance, guards the body and strikes with a short blade. Requires metalworking and barracks infrastructure.',
 veteranRifle:'An experienced firearm infantry unit. A tall dark cap, broad epaulets and decorated coat distinguish veterans from the regular battle line. Recruited after reaching the Industrial Age.',
 grenadier:'A short-range explosive specialist. Winds up, throws a grenade on an arc and prepares another charge. Useful against clustered targets; the thrown object is separate from the hand after release.',
 pikeman:'A trained anti-cavalry infantry unit with an exceptionally long pike. Controls approach lanes and supports other troops. Its reach is valuable against charging riders but cumbersome in dispersed fighting.',
 marksman:'A precision firearm specialist. Prioritizes deliberate ranged shots over close combat. A feathered broad-brim hat, shoulder cape and longer rifle distinguish it from regular line infantry.',
 skirmisher:'A mobile firearm infantry unit. Harasses enemy formations and favors movement over heavy armor. Operates from the barracks after firearms become available.',
 shieldBearer:'A defensive infantry unit with a large shield and short blade. Protects advancing formations from frontal attacks. Its broad shield is the key visual cue for this role.',
 saboteur:'A specialist carrying demolition charges. Approaches structures or equipment and throws an explosive rather than fighting as ordinary line infantry. Requires advanced military infrastructure.',
 archer:'A bow-armed ranged unit. Braces the bow with one hand, draws the string with the other, releases an arrow and nocks the next. Its quiver, light clothing and tall bow distinguish it from gunpowder infantry.',
 crossbow:'A mechanically assisted ranged unit. Shoulders a horizontal crossbow, releases a bolt and reloads the stock. Available after medieval weaponmaking, with greater protection than an early archer.',
 medic:'A support worker for injured troops. Carries a treatment bag and contributes healing rather than frontline damage. Requires a developed civic or medical institution.',
 engineer:'A technical military worker. Builds and repairs military equipment and field structures. Carries a hammer and engineering supplies instead of a standard infantry weapon.',
 explorer:'A lightly equipped reconnaissance unit. Reveals terrain, locates resources and investigates supply caches. Prioritizes mobility and exploration over holding a battle line.',
 factionGuard:'An elite League infantry guard. Uses heavier armor, a shield and a blade to protect valuable positions. Requires an established military center and later technology.',
 contractUnit:'A hired close-combat specialist recruited through the contract hall. Provides an alternative military role at a resource cost. Its equipment follows its contract rather than basic barracks progression.',
 allianceUnit:'An allied spear-and-shield soldier. Supports a force through diplomacy and embassy access. Combines reach with frontal protection.',
 commander:'A command and support officer. Coordinates nearby troops and represents a high-value military unit. Carries distinctive officer equipment and should be protected from concentrated attacks.',
 cavalry:'A lance-armed mounted soldier. Lowers the lance for a forward attack while the other hand controls the reins. Boots remain in the stirrups and the lance clears the rider’s leg.',
 lightRider:'A lightly armored mounted raider. Uses a saber and speed to pursue vulnerable targets. Trades protection for mobility and is trained at the stable.',
 dragoon:'A mounted firearm soldier. Carries a rifle on the mount and brings it into a two-handed firing pose. Combines mounted mobility with ranged combat during the firearm era.',
 cuirassRider:'A heavily protected mounted swordsman. Uses a saber for close combat and a metal breastplate for protection. Requires later cavalry training and more investment than a light rider.',
 mountedScout:'A mounted reconnaissance unit. Keeps both hands available for riding and observation. Its role is scouting, not pretending an unarmed rider has a lance attack.',
 cannon:'A crew-operated field gun. A loader brings ammunition, a rammer prepares the bore, and the gun fires a visible round with recoil. Crew clear the muzzle before discharge.',
 howitzer:'An artillery piece intended for arcing fire. Its shorter, wider barrel distinguishes it from a long field cannon. Requires a workshop and trained crew.',
 scatterGun:'A broad-bore close-defense artillery piece. Protects nearby troops against concentrated approaches. Its carriage supports a heavier muzzle than a standard field gun.',
 mortar:'A short, steeply elevated siege weapon. Launches rounds in an arc toward fortified targets. It requires protection while its crew loads and fires.',
 rocketCart:'A mobile rack of unguided rockets. Fires visible rockets from a raised launch frame. Useful for area pressure, with a conspicuous reload cycle.',
 ramWagon:'A protected timber battering ram. Moves a heavy striking beam against gates and walls at direct-contact range. Its roof shields the assembly during the approach.',
 siegeTower:'A tall mobile assault structure. Carries troops toward fortified positions and provides elevated access. Its multiple platforms and large timber frame make it a slow, conspicuous target.',
 supplyWagon:'A cargo wagon supporting troops away from home. Carries provisions and equipment. It is logistical support rather than a direct-combat unit.',
 builderWagon:'A mobile construction team’s wagon. Carries ladders, tools and building supplies for remote development. Its ladder rack distinguishes it from a trade wagon.',
 trader:'A commercial wagon traveling between trade facilities. Generates economic value through route movement. Cargo security and access matter more than combat strength.',
 sapperTeam:'A paired engineering detachment. Performs demolition and close siege work near enemy structures. Two equipped specialists operate together rather than a single rifleman.',
 mobileFieldwork:'A transported defensive barrier. Establishes a temporary protected position using stakes and timber. Supports a force’s positioning rather than long-range attack.',
 ship:'A multipurpose coastal cutter. Carries a small gun battery and rigging suitable for coastal patrol. It is smaller and less heavily armed than a frigate.',
 fishingBoat:'A dedicated food-gathering vessel. Works fish patches and returns the catch to shore facilities. Evolves from a small paddled craft to a dedicated sail-powered fishing vessel.',
 tradeShip:'A wide cargo vessel for waterborne commerce. Broad holds and cargo stacks maximize carrying capacity. Larger later forms gain deeper cargo holds and an elevated stern cabin.',
 transport:'A troop-carrying vessel with an open passenger deck and landing ramp. Moves land units across water. Its broad hull and boarding ramp distinguish it from a gun-carrying warship.',
 sloop:'A small, narrow patrol vessel. Uses a light armament and compact rig for coastal screening. Faster and less durable than a large frigate.',
 frigate:'A large naval combat vessel. Multiple masts, raised decks and a long row of broadside guns define its silhouette. Designed for sustained ship-to-ship fighting.',
 bombardVessel:'A broad-beamed floating siege platform. A heavy central mortar trades speed and cargo capacity for bombardment. Its low working deck leaves room around the weapon.',
 fireCraft:'A small expendable incendiary vessel. Carries volatile cargo for close attacks on hostile ships. Its low hull and exposed barrels identify its hazardous role.',
 villager:'A male civilian worker. Gathers berries, mines, farms, fishes, processes meat, chops trees and builds. Spawns as one of the two worker appearances, with a plain face, ears and faction-colored clothing.',
 villagerFemale:'A female civilian worker with the same capabilities as the male worker. Uses the same resource and construction actions, with a different outfit and hair silhouette. Gender is chosen at worker creation and does not change gathering ability.',
 sheep:'A domesticated food animal identified by its owner-colored collar. Can graze, move, flee and be killed. Meat remains available on the carcass until workers finish collecting it.',
 deer:'A wild huntable food animal. Wanders and grazes in suitable habitat, flees danger and leaves a harvestable carcass when killed. Antlers and slender legs distinguish it from livestock.',
 wolf:'A hostile wild predator. Roams remote habitat and threatens nearby passing units. Its attack should use a body lunge and opening jaw rather than a head-only bob.',
 scoutAnimal:'A trained scouting hound with a faction collar. Supports reconnaissance and close biting attacks. Its lower body, long muzzle and tail distinguish it from hoofed food animals.',
 stoneMine:'A finite outcrop of fractured stone. Workers remove entire rock chunks as the deposit is mined. Exhaustion leaves no usable deposit instead of merely recoloring the surface.',
 mine:'A finite gold-bearing outcrop. Irregular mineral seams lie between fractured rock slabs. Mining removes complete chunks of rock and ore until the whole deposit is exhausted.',
 tree:'A harvestable broadleaf tree with a branching trunk and leaf sprays. Provides timber; the felled state removes the leafy crown from rendering and leaves the fallen trunk and stump.',
 pine:'A harvestable conifer with radial branches and needle sprays. Provides timber in forest habitats and sways in wind. Its felled state uses a bare trunk to reduce unnecessary foliage rendering.',
 treeHalfCut:'A felled resource tree after the main trunk has been severed. The crown falls onto the ground and foliage is omitted. Remaining timber can be processed before the stump is cleared.',
 stump:'The remaining base of a harvested tree. Marks where the tree stood after the trunk has been processed. It provides a distinct final visual state before clearing.',
 logPile:'Stacked cut timber awaiting storage or transport. A resource and logistics prop for lumber yards and worker deliveries. Logs retain visible round sections rather than resembling crates.',
 bush:'A non-berry shrub used for habitat and landscape detail. Branches and leaf sprays create a small irregular silhouette. It does not imply a food source.',
 berries:'A food-bearing shrub with visible red fruit. Workers gather from reachable branches and carry the harvest in a basket. Resource placement reserves its gathering area.',
 treasure:'An original supply cache for exploration scenarios. Represents recoverable cargo or a scripted reward. It is a discoverable object rather than a production building.',
 fish:'A fishing habitat marker shown through intermittent fish jumps. Marks a food source for fishing boats and nearby shore workers. The water remains opaque rather than revealing a circular underwater aquarium.',
 bird:'An ambient coastal gull. Uses wing motion and flight paths to bring the sky to life. It is cosmetic wildlife and does not affect resource gathering or combat.'
};
export function ageDescription(kind:string){const age=unlockAge[kind];return age?`Unlocks in the ${eras[age-1]} Age.${retireAge[kind]?` Available through the ${eras[retireAge[kind]-1]} Age.`:''}`:'Natural resource or scenery; no technology unlock.';}
